// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/guruforge/CreatorFlow.tsx": () => import("../components/mockups/guruforge/CreatorFlow.tsx"),
  "./components/mockups/guruforge/GuruProfile.tsx": () => import("../components/mockups/guruforge/GuruProfile.tsx"),
  "./components/mockups/guruforge/Landing.tsx": () => import("../components/mockups/guruforge/Landing.tsx"),
  "./components/mockups/guruforge/Marketplace.tsx": () => import("../components/mockups/guruforge/Marketplace.tsx")
};
