// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/guruforge/CreatorFlow.tsx": () => import("../components/mockups/guruforge/CreatorFlow.tsx"),
  "./components/mockups/guruforge/GuruProfile.tsx": () => import("../components/mockups/guruforge/GuruProfile.tsx"),
  "./components/mockups/guruforge/Landing.tsx": () => import("../components/mockups/guruforge/Landing.tsx"),
  "./components/mockups/guruforge/LandingCompact.tsx": () => import("../components/mockups/guruforge/LandingCompact.tsx"),
  "./components/mockups/guruforge/LandingEphemeral.tsx": () => import("../components/mockups/guruforge/LandingEphemeral.tsx"),
  "./components/mockups/guruforge/LandingFused.tsx": () => import("../components/mockups/guruforge/LandingFused.tsx"),
  "./components/mockups/guruforge/LandingNeoMinimal.tsx": () => import("../components/mockups/guruforge/LandingNeoMinimal.tsx"),
  "./components/mockups/guruforge/LandingSplit.tsx": () => import("../components/mockups/guruforge/LandingSplit.tsx"),
  "./components/mockups/guruforge/LandingStagger.tsx": () => import("../components/mockups/guruforge/LandingStagger.tsx"),
  "./components/mockups/guruforge/Marketplace.tsx": () => import("../components/mockups/guruforge/Marketplace.tsx"),
  "./components/mockups/guruforge/MarketplaceEditorial.tsx": () => import("../components/mockups/guruforge/MarketplaceEditorial.tsx"),
  "./components/mockups/guruforge/MarketplaceLeaderboard.tsx": () => import("../components/mockups/guruforge/MarketplaceLeaderboard.tsx"),
  "./components/mockups/guruforge/MarketplaceSocial.tsx": () => import("../components/mockups/guruforge/MarketplaceSocial.tsx"),
  "./components/mockups/guruforge/MarketplaceSpeed.tsx": () => import("../components/mockups/guruforge/MarketplaceSpeed.tsx")
};
